name: build

on:
  push:
    branchs: [main]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2
    
      - name: Env
        run: ./configure

      - name: Build
        run: make


